name: Auto Merge
description: Auto Merges an open PR given a Branch Name
inputs:
  repoOwner:
    required: false
    description: Pull Request Number
    default: bandwidth
  repoName:
    required: true
    description: Pull Request Number
  prNumber:
    required: true
    description: Pull Request Number
  checkNames:
    required: false
    description: Checks to Await Before Auto-Merging
  token:
    required: true
    description: Github Token
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install and Run Script
      run: |
        cd ${{ github.action_path }}
        npm install && npm run start
      env:
        token: ${{ inputs.token }}
      shell: bash

